/*
 * Generated by tools/gen_defs.py from profile/ardudeck.xml. Do not edit.
 *
 * Every id, payload length and CRC extra here was computed, never typed. The
 * generator refuses to run unless it first reproduces the published extras for
 * the standard messages, so these values are as trustworthy as those are.
 */

#ifndef AD_MSG_DEFS_H
#define AD_MSG_DEFS_H

#include <stdint.h>

typedef struct {
  uint32_t id;
  uint8_t  length;   /* base payload; the SDK never fills extensions */
  uint8_t  crc_extra;
} ad_msg_def_t;

#define AD_MSG_HEARTBEAT            ((ad_msg_def_t){     0,   9,  50 })  /* HEARTBEAT */
#define AD_MSG_SYS_STATUS           ((ad_msg_def_t){     1,  31, 124 })  /* SYS_STATUS */
#define AD_MSG_GPS_RAW_INT          ((ad_msg_def_t){    24,  30,  24 })  /* GPS_RAW_INT */
#define AD_MSG_ATTITUDE             ((ad_msg_def_t){    30,  28,  39 })  /* ATTITUDE */
#define AD_MSG_GLOBAL_POSITION_INT  ((ad_msg_def_t){    33,  28, 104 })  /* GLOBAL_POSITION_INT */
#define AD_MSG_VFR_HUD              ((ad_msg_def_t){    74,  20,  20 })  /* VFR_HUD */
#define AD_MSG_PARAM_VALUE          ((ad_msg_def_t){    22,  25, 220 })  /* PARAM_VALUE */
#define AD_MSG_PARAM_REQUEST_READ   ((ad_msg_def_t){    20,  20, 214 })  /* PARAM_REQUEST_READ */
#define AD_MSG_PARAM_REQUEST_LIST   ((ad_msg_def_t){    21,   2, 159 })  /* PARAM_REQUEST_LIST */
#define AD_MSG_PARAM_SET            ((ad_msg_def_t){    23,  23, 168 })  /* PARAM_SET */
#define AD_MSG_COMMAND_LONG         ((ad_msg_def_t){    76,  33, 152 })  /* COMMAND_LONG */
#define AD_MSG_COMMAND_ACK          ((ad_msg_def_t){    77,   3, 143 })  /* COMMAND_ACK */
#define AD_MSG_MISSION_ITEM_INT     ((ad_msg_def_t){    73,  37,  38 })  /* MISSION_ITEM_INT */
#define AD_MSG_MISSION_REQUEST_INT  ((ad_msg_def_t){    51,   4, 196 })  /* MISSION_REQUEST_INT */
#define AD_MSG_MISSION_REQUEST_LIST ((ad_msg_def_t){    43,   2, 132 })  /* MISSION_REQUEST_LIST */
#define AD_MSG_MISSION_COUNT        ((ad_msg_def_t){    44,   4, 221 })  /* MISSION_COUNT */
#define AD_MSG_MISSION_ACK          ((ad_msg_def_t){    47,   3, 153 })  /* MISSION_ACK */
#define AD_MSG_MISSION_CLEAR_ALL    ((ad_msg_def_t){    45,   2, 232 })  /* MISSION_CLEAR_ALL */
#define AD_MSG_MISSION_CURRENT      ((ad_msg_def_t){    42,   2,  28 })  /* MISSION_CURRENT */
#define AD_MSG_RC_CHANNELS          ((ad_msg_def_t){    65,  42, 118 })  /* RC_CHANNELS */
#define AD_MSG_STATUSTEXT           ((ad_msg_def_t){   253,  51,  83 })  /* STATUSTEXT */
#define AD_MSG_HOME_POSITION        ((ad_msg_def_t){   242,  52, 104 })  /* HOME_POSITION */
#define AD_MSG_SET_MODE             ((ad_msg_def_t){    11,   6,  89 })  /* SET_MODE */
#define AD_MSG_CAL_CONTROL          ((ad_msg_def_t){ 43008,  19, 117 })  /* ARDUDECK_CAL_CONTROL */
#define AD_MSG_CAL_DECLARE          ((ad_msg_def_t){ 43005, 186, 223 })  /* ARDUDECK_CAL_DECLARE */
#define AD_MSG_CAL_POSE             ((ad_msg_def_t){ 43006,  50, 214 })  /* ARDUDECK_CAL_POSE */
#define AD_MSG_CAL_PROGRESS         ((ad_msg_def_t){ 43009,  79,  42 })  /* ARDUDECK_CAL_PROGRESS */
#define AD_MSG_CAL_RESULT           ((ad_msg_def_t){ 43010,  85,  48 })  /* ARDUDECK_CAL_RESULT */
#define AD_MSG_CAL_TRACK            ((ad_msg_def_t){ 43007,  66,  24 })  /* ARDUDECK_CAL_TRACK */
#define AD_MSG_MANIFEST             ((ad_msg_def_t){ 43000,  94, 144 })  /* ARDUDECK_MANIFEST */
#define AD_MSG_MISSION_CMDS         ((ad_msg_def_t){ 43002,  65, 219 })  /* ARDUDECK_MISSION_CMDS */
#define AD_MSG_MODE                 ((ad_msg_def_t){ 43001,  21, 219 })  /* ARDUDECK_MODE */
#define AD_MSG_PARAM_META           ((ad_msg_def_t){ 43003, 124, 203 })  /* ARDUDECK_PARAM_META */
#define AD_MSG_PARAM_OPTION         ((ad_msg_def_t){ 43004,  52,  82 })  /* ARDUDECK_PARAM_OPTION */
#define AD_MSG_REQUEST              ((ad_msg_def_t){ 43011,   5,  70 })  /* ARDUDECK_REQUEST */

/* Largest payload the SDK ever builds, so the frame buffer can be sized exactly. */
#define AD_MAX_PAYLOAD 186

#endif /* AD_MSG_DEFS_H */
